#!/usr/bin/env python3

import sys
import os

def check_input():
    if not os.path.exists(".grip"):
        print("grip-log: error: grip repository directory .grip not found")
        sys.exit()

    if len(sys.argv) != 1:
        print("usage: grip-log")
        sys.exit()

def read_log():
    source_dir = os.path.join(".grip", "commits")
    commits = sorted(os.listdir(source_dir), reverse=True)

    for i in range(len(commits)):
        target = os.path.join(source_dir, commits[i])
        msg = os.path.join(target, "message")
        with open(msg, 'r') as file:
            content = file.readline()
        
        print(f"{commits[i]} {content}")

check_input()
read_log()